# using baseURL causes issues when using custom CSS
# baseURL = 'https://hosack.me'
relativeURLs = true
languageCode = 'en-us'
title = 'Matt Hosack'
theme = 'cactus'
disqusShortname = 'hosack-me'

[params]
    subtitle = 'Software Engineer'
    mainSection = 'about'
    mainSectionTitle = 'Writings'
    description = 'Welcome to the crossroads where rhythm meets code, and circuits hum with creativity. This space is a reflection of a life devoted to exploring the intersections of music and technology. From the nuances of sound design to the art of crafting elegant software solutions, my journey weaves these passions together. Here, I share thoughts, experiments, and insights drawn from years spent navigating the worlds of both artistry and engineering. Dive in, and explore the stories and ideas that bridge melody and innovation.'
    tocInline = true
    colortheme = 'dark'
    showProjectsList = true

[params.contact]
    email = 'hosack.matt@gmail.com'
    phone = '+4915772113103'

[params.comments]
    enabled = true

[[menu.main]]
    identifier = 'about'
    name = 'About'
    url = '/about/'
    weight = 1

[[menu.main]]
    identifier = 'posts'
    name = 'Posts'
    url = '/posts/'
    weight = 3

[[menu.main]]
    identifier = 'resume'
    name = 'Resume'
    url = '/resume/'
    weight = 2

[markup]
    [markup.highlight]
        codeFences = true
        guessSyntax = true
        style = 'catppuccin-macchiato'

[[params.social]]
    name = 'github'
    link = 'https://github.com/hosackm'

[[params.social]]
    name = 'email'
    link = 'hosack.matt@gmail.com' # no need for 'mailto:' at the start

[[params.social]]
    name = 'linkedin'
    link = 'https://www.linkedin.com/in/matthosack/'
